Repository ogcio/govie-ds, pull requests merged in 2024-12, with the labels that each got.

#349 docs: add breadcrumbs link
  apps/docs/content/3-components/2-library/breadcrumbs.mdx
Labels: documentation

#340 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#355 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#351 feat: react table component
  packages/design/tailwind/css/components.css
  packages/react/ds/src/checkbox/checkbox.tsx
  packages/react/ds/src/table/caption.tsx
  packages/react/ds/src/table/table-data.tsx
  packages/react/ds/src/table/table-header.tsx
  packages/react/ds/src/table/table-row.tsx
  packages/react/ds/src/table/table.stories.tsx
  packages/react/ds/src/table/table.tsx
Labels: documentation, enhancement

#358 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#362 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
Labels: autorelease: pending

#356 feat: Progress Stepper component
  apps/docs/content/3-components/2-library/progress-stepper.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  examples/nextjs/src/app/page.tsx
  examples/wagtail/core/jinja/home_page.jinja
  packages/design/tailwind/css/components.css
  packages/html/ds/src/progress-stepper/progress-stepper.html
  packages/html/ds/src/progress-stepper/progress-stepper.schema.ts
  packages/html/ds/src/progress-stepper/progress-stepper.stories.ts
  packages/html/ds/src/progress-stepper/progress-stepper.test.ts
  packages/react/ds/src/icon/icon.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/src/progress-stepper/progress-stepper.stories.tsx
  packages/react/ds/src/progress-stepper/progress-stepper.test.tsx
  packages/react/ds/src/progress-stepper/progress-stepper.tsx
  packages/react/ds/src/progress-stepper/types.ts
Labels: documentation, enhancement

#363 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#359 feat: table component html and macro implementation
  apps/docs/content/3-components/2-library/table.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  examples/wagtail/core/jinja/home_page.jinja
  packages/design/tailwind/css/components.css
  packages/html/ds/src/table/table.html
  packages/html/ds/src/table/table.schema.ts
  packages/html/ds/src/table/table.stories.ts
  packages/html/ds/src/table/table.test.ts
  packages/react/ds/src/index.ts
  packages/react/ds/src/table/caption.tsx
  packages/react/ds/src/table/table.stories.tsx
Labels: documentation, enhancement

#360 feat: accordion component
  packages/html/ds/src/accordion/accordion-schema.ts
  packages/html/ds/src/accordion/accordion.html
  packages/html/ds/src/accordion/accordion.stories.ts
  packages/html/ds/src/accordion/accordion.ts
  packages/html/ds/src/common/instances.ts
  packages/html/ds/src/index.ts
  packages/react/ds/src/accordion/accordion-item.tsx
  packages/react/ds/src/accordion/accordion.stories.tsx
  packages/react/ds/src/accordion/accordion.tsx
Labels: documentation, enhancement

#368 feat: button and links
  apps/docs/src/app/page.tsx
  apps/docs/src/components/document/common/card.tsx
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/components/form/button.tsx
  apps/docs/src/components/typography/link.tsx
  packages/html/ds/src/link/link.html
  packages/html/ds/src/link/link.schema.ts
  packages/html/ds/src/link/link.stories.ts
  packages/react/ds/src/icon/icons.ts
  packages/react/ds/src/link/link.stories.tsx
  packages/react/ds/src/link/link.tsx
Labels: documentation, enhancement

#367 feat: add react tooltip component
  apps/docs/content/3-components/2-library/tooltip.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  packages/design/tailwind/css/components.css
  packages/react/ds/src/index.ts
  packages/react/ds/src/tooltip/tooltip.stories.tsx
  packages/react/ds/src/tooltip/tooltip.test.tsx
  packages/react/ds/src/tooltip/tooltip.tsx
Labels: documentation, enhancement

#371 feat: add html and macro for tooltip
  apps/docs/content/3-components/2-library/tooltip.mdx
  examples/wagtail/core/jinja/home_page.jinja
  packages/design/tailwind/css/components.css
  packages/html/ds/src/common/instances.ts
  packages/html/ds/src/index.ts
  packages/html/ds/src/tooltip/tooltip.html
  packages/html/ds/src/tooltip/tooltip.schema.ts
  packages/html/ds/src/tooltip/tooltip.stories.ts
  packages/html/ds/src/tooltip/tooltip.test.ts
  packages/html/ds/src/tooltip/tooltip.ts
  packages/html/storybook/.storybook/preview.tsx
  packages/react/ds/src/tooltip/tooltip.stories.tsx
Labels: documentation, enhancement

#377 chore: update table stories with tooltip
  apps/docs/content/3-components/2-library/tooltip.mdx
  packages/design/tailwind/css/components.css
  packages/html/ds/src/table/table.stories.ts
  packages/react/ds/src/table/table.stories.tsx
  packages/react/ds/src/tooltip/tooltip.stories.tsx
  packages/react/ds/src/tooltip/tooltip.test.tsx
  packages/react/ds/src/tooltip/tooltip.tsx
Labels: documentation, enhancement

#375 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#379 chore(ci): release main
  .release-please-manifest.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending
