Repository ogcio/govie-ds, pull requests merged in 2024-10, with the labels that each got.

#254 feat: add html file-upload component
  apps/docs/src/lib/components.ts
  examples/wagtail/core/jinja/home_page.jinja
  packages/html/ds/src/common/render.ts
  packages/html/ds/src/file-upload/file-upload.html
  packages/html/ds/src/file-upload/file-upload.schema.ts
  packages/html/ds/src/file-upload/file-upload.stories.ts
  packages/html/ds/src/file-upload/file-upload.test.ts
  packages/react/ds/src/file-upload/file-upload.stories.tsx
Labels: documentation, enhancement

#256 chore: add pull request template
  .github/workflows/PULL_REQUEST_TEMPLATE/bugfix_template.md
  .github/workflows/PULL_REQUEST_TEMPLATE/feature_template.md
Labels: enhancement

#249 chore(ci): release main
  .release-please-manifest.json
  packages/build/prettier-config/CHANGELOG.md
  packages/build/prettier-config/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#261 chore(ci): release main
  .release-please-manifest.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#266 chore: update schema description
  packages/html/ds/src/file-upload/file-upload.schema.ts
Labels: bug

#264 feat: html button component
  packages/design/tailwind/css/components.css
  packages/html/ds/src/button/button-schema.ts
  packages/html/ds/src/button/button.html
  packages/html/ds/src/button/button.stories.ts
  packages/html/ds/src/button/button.test.ts
  packages/html/ds/src/button/helpers.html
  packages/html/storybook/.storybook/preview.tsx
  packages/html/storybook/tailwind.config.ts
Labels: enhancement

#263 chore(ci): release main
  .release-please-manifest.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#281 chore(ci): release main
  .release-please-manifest.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#283 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#279 feat: radio component
  apps/docs/content/3-components/2-library/32-radio-button.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/components/form/radio.tsx
  apps/docs/src/lib/components.ts
  examples/nextjs/src/app/page.tsx
  examples/vite/src/application.tsx
  examples/wagtail/core/jinja/home_page.jinja
  examples/wagtail/core/jinja/vars.jinja
  packages/design/tailwind/css/components.css
  packages/html/ds/src/common/instances.ts
  packages/html/ds/src/index.ts
  packages/html/ds/src/radio/helpers.html
  packages/html/ds/src/radio/radio.html
  packages/html/ds/src/radio/radio.schema.ts
  packages/html/ds/src/radio/radio.stories.ts
  packages/html/ds/src/radio/radio.test.ts
  packages/html/ds/src/radio/radio.ts
  packages/html/ds/src/radio/radios-group.html
  packages/react/ds/package.json
  packages/react/ds/src/checkbox/checkboxes-group.tsx
  packages/react/ds/src/icon-button/icon-button.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/src/radio/radio.stories.tsx
  packages/react/ds/src/radio/radio.tsx
  packages/react/ds/src/radio/radios-group.tsx
  packages/react/ds/src/radio/types.ts
  packages/react/ds/tsconfig.json
  packages/react/ds/vite.config.ts
  pnpm-lock.yaml
Labels: documentation, enhancement

#286 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#291 chore(ci): release main
  .release-please-manifest.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#293 feat: update HTML and React Card component with Inset, Tag, Action and Subheading
  apps/docs/content/3-components/2-library/7-card.mdx
  apps/docs/public/card_300x180_sample.png
  apps/docs/public/card_600x360_sample.png
  examples/vite/src/application.tsx
  packages/design/tailwind/css/components.css
  packages/html/ds/scripts/build-properties.ts
  packages/html/ds/src/card/card.html
  packages/html/ds/src/card/card.schema.ts
  packages/html/ds/src/card/card.stories.ts
  packages/html/ds/src/card/card.test.ts
  packages/html/ds/src/link/link.html
  packages/html/ds/src/link/link.schema.ts
  packages/html/ds/src/link/link.stories.ts
  packages/react/ds/src/card/card.stories.tsx
  packages/react/ds/src/card/card.tsx
Labels: bug, documentation, enhancement

#295 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#298 chore: expose icon type to accept string
  packages/html/ds/src/icon/icon.schema.ts
  packages/react/ds/src/icon/icon.tsx
Labels: bug

#302 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#305 docs: add icon resource page
  apps/docs/content/3-components/2-library/22-icon.mdx
  apps/docs/content/5-resources/5-icons.mdx
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/components/document/resources/icon-grid-layout.tsx
  packages/html/ds/src/icon/icon.html
Labels: documentation, enhancement

#304 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending
