Repository ogcio/govie-ds, pull requests merged in 2024-09, with the labels that each got.

#184 feat: add html link component
  examples/wagtail/core/jinja/home_page.jinja
  examples/wagtail/db.sqlite3
  packages/html/ds/src/header/header.test.ts
  packages/html/ds/src/link/link.html
  packages/html/ds/src/link/link.schema.ts
  packages/html/ds/src/link/link.stories.ts
  packages/html/ds/src/link/link.test.ts
  packages/html/ds/styles.css
Labels: enhancement

#191 ci: install nx html storybook
  .github/workflows/deploy-html-storybook-prod.yml
Labels: bug

#197 revert: dark mode on HTML link component
  packages/html/ds/src/link/link.html
  packages/html/ds/src/link/link.schema.ts
  packages/html/ds/src/link/link.stories.ts
  packages/html/ds/src/link/link.test.ts
  packages/html/ds/styles.css
Labels: revert

#187 feat: footer component
  examples/wagtail/core/jinja/home_page.jinja
  examples/wagtail/core/jinja/vars.jinja
  examples/wagtail/core/settings/base.py
  packages/html/ds/scripts/build-properties.ts
  packages/html/ds/scripts/process-macros-plugin.ts
  packages/html/ds/src/footer/footer.html
  packages/html/ds/src/footer/footer.schema.ts
  packages/html/ds/src/footer/footer.stories.ts
  packages/html/ds/src/footer/helpers.html
  packages/html/ds/src/storybook/storybook.tsx
  packages/html/macro/src/macro.ts
Labels: enhancement

#186 feat: enable tailwind in react components
  examples/nextjs/src/app/layout.tsx
  examples/nextjs/src/app/page.tsx
  examples/vite/src/application.tsx
  packages/design/tailwind/src/create-theme.ts
  packages/html/storybook/.storybook/preview.tsx
  packages/html/storybook/index.html
  packages/react/ds/package.json
  packages/react/ds/src/container/container.module.css
  packages/react/ds/src/container/container.tsx
  packages/react/ds/src/footer/footer.module.css
  packages/react/ds/src/footer/footer.tsx
  packages/react/ds/src/header/header.module.css
  packages/react/ds/src/header/header.tsx
  packages/react/ds/src/heading/heading.module.css
  packages/react/ds/src/heading/heading.tsx
  packages/react/ds/src/icon-button/icon-button.module.css
  packages/react/ds/src/icon-button/icon-button.stories.tsx
  packages/react/ds/src/icon-button/icon-button.tsx
  packages/react/ds/src/icon/icon.stories.tsx
  packages/react/ds/src/link/link.module.css
  packages/react/ds/src/link/link.tsx
  packages/react/ds/src/paragraph/paragraph.tsx
  packages/react/ds/src/phase-banner/phase-banner.module.css
  packages/react/ds/src/phase-banner/phase-banner.tsx
  packages/react/ds/src/text/heading.module.css
  packages/react/ds/src/text/paragraph.module.css
  packages/react/ds/src/text/text.tsx
  packages/react/ds/styles.css
  packages/react/ds/tailwind.config.ts
  packages/react/storybook/.storybook/main.ts
  packages/react/storybook/.storybook/preview-head.html
  packages/react/storybook/.storybook/preview.ts
  packages/react/storybook/docs/installation.mdx
  packages/react/storybook/index.html
  packages/react/storybook/package.json
  packages/react/storybook/postcss.config.mjs
  packages/react/storybook/tailwind.config.ts
  pnpm-lock.yaml
Labels: enhancement

#200 feat: container component
  examples/wagtail/core/jinja/home_page.jinja
  packages/html/ds/src/container/container.html
  packages/html/ds/src/container/container.schema.ts
  packages/html/ds/src/container/container.stories.ts
  packages/html/ds/src/container/container.test.ts
Labels: enhancement

#203 docs: update copy code block and meta tag
  packages/html/storybook/.storybook/preview.tsx
  packages/html/storybook/docs/introduction.mdx
  packages/html/storybook/docs/precompiled.mdx
Labels: documentation

#202 chore: enable html in paragraph
  examples/wagtail/core/jinja/home_page.jinja
  packages/html/ds/src/paragraph/paragraph.html
  packages/html/ds/src/paragraph/paragraph.test.ts
Labels: enhancement

#194 chore: add chromatic
  .github/workflows/chromatic.yml
  packages/html/storybook/package.json
  packages/html/storybook/static/macros/footer/footer.html
  packages/html/storybook/static/macros/footer/helpers.html
  packages/html/storybook/static/macros/header/header.html
  packages/html/storybook/static/macros/heading/heading.html
  packages/html/storybook/static/macros/link/link.html
  packages/html/storybook/static/macros/paragraph/paragraph.html
  packages/react/storybook/package.json
  pnpm-lock.yaml
Labels: enhancement

#206 docs: add paragraph, link and container HTML guidelines
  apps/docs/content/3-components/2-library/10-container.mdx
  apps/docs/content/3-components/2-library/11-date-input.mdx
  apps/docs/content/3-components/2-library/12-details.mdx
  apps/docs/content/3-components/2-library/13-error-summary.mdx
  apps/docs/content/3-components/2-library/14-file-upload.mdx
  apps/docs/content/3-components/2-library/15-footer.mdx
  apps/docs/content/3-components/2-library/16-header.mdx
  apps/docs/content/3-components/2-library/17-heading.mdx
  apps/docs/content/3-components/2-library/19-icon.mdx
  apps/docs/content/3-components/2-library/20-inset-text.mdx
  apps/docs/content/3-components/2-library/21-label.mdx
  apps/docs/content/3-components/2-library/21-link.mdx
  apps/docs/content/3-components/2-library/22-link.mdx
  apps/docs/content/3-components/2-library/23-list.mdx
  apps/docs/content/3-components/2-library/24-modal.mdx
  apps/docs/content/3-components/2-library/25-notification-panel.mdx
  apps/docs/content/3-components/2-library/26-pagination.mdx
  apps/docs/content/3-components/2-library/27-panel.mdx
  apps/docs/content/3-components/2-library/27-paragraph.mdx
  apps/docs/content/3-components/2-library/28-paragraph.mdx
  apps/docs/content/3-components/2-library/29-phase-banner.mdx
  apps/docs/content/3-components/2-library/30-progress-stepper.mdx
  apps/docs/content/3-components/2-library/31-radio-button.mdx
  apps/docs/content/3-components/2-library/32-section-break.mdx
  apps/docs/content/3-components/2-library/33-select.mdx
  apps/docs/content/3-components/2-library/34-step-by-step-navigation.mdx
  apps/docs/content/3-components/2-library/35-summary-list.mdx
  apps/docs/content/3-components/2-library/36-table.mdx
  apps/docs/content/3-components/2-library/37-tabs.mdx
  apps/docs/content/3-components/2-library/38-tag.mdx
  apps/docs/content/3-components/2-library/39-task-list.mdx
  apps/docs/content/3-components/2-library/40-text-input.mdx
  apps/docs/content/3-components/2-library/41-textarea.mdx
  apps/docs/content/3-components/2-library/42-tick.mdx
  apps/docs/content/3-components/2-library/43-tooltip.mdx
  apps/docs/content/3-components/2-library/44-warning-text.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/design-system-benefits.tsx
  apps/docs/src/lib/components.ts
Labels: documentation

#212 feat: add text input along with label, hint-text, error-text and form-group components.
  apps/docs/content/3-components/2-library/21-label.mdx
  apps/docs/content/3-components/2-library/40-text-input.mdx
  apps/docs/dictionary.txt
  apps/docs/src/lib/components.ts
  examples/vite/src/application.tsx
  packages/react/ds/src/error-text/error-text.stories.tsx
  packages/react/ds/src/error-text/error-text.tsx
  packages/react/ds/src/form-group/form-group.tsx
  packages/react/ds/src/hint-text/hint-text.stories.tsx
  packages/react/ds/src/hint-text/hint-text.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/src/label/label.stories.tsx
  packages/react/ds/src/label/label.tsx
  packages/react/ds/src/text-input/text-input.stories.tsx
  packages/react/ds/src/text-input/text-input.tsx
  packages/react/storybook/.storybook/main.ts
Labels: enhancement

#222 feat: add html text input component
  packages/html/ds/src/error-text/error-text.html
  packages/html/ds/src/error-text/error-text.schema.ts
  packages/html/ds/src/error-text/error-text.stories.ts
  packages/html/ds/src/error-text/error-text.test.ts
  packages/html/ds/src/hint-text/hint-text.html
  packages/html/ds/src/hint-text/hint-text.schema.ts
  packages/html/ds/src/hint-text/hint-text.stories.ts
  packages/html/ds/src/hint-text/hint-text.test.ts
  packages/html/ds/src/label/label.html
  packages/html/ds/src/label/label.schema.ts
  packages/html/ds/src/label/label.stories.ts
  packages/html/ds/src/label/label.test.ts
  packages/html/ds/src/text-input/text-input.html
  packages/html/ds/src/text-input/text-input.schema.ts
  packages/html/ds/src/text-input/text-input.stories.ts
  packages/html/ds/src/text-input/text-input.test.ts
  packages/html/storybook/.storybook/preview.tsx
Labels: documentation, enhancement

#226 feat: add react textarea component
  apps/docs/content/3-components/2-library/41-textarea.mdx
  apps/docs/src/lib/components.ts
  packages/react/ds/src/index.ts
  packages/react/ds/src/textarea/textarea.stories.tsx
  packages/react/ds/src/textarea/textarea.tsx
Labels: documentation, enhancement

#221 fix: html library unit test
  packages/html/ds/src/common/render.ts
  packages/html/ds/src/footer/footer.html
  packages/html/ds/src/footer/footer.test.ts
  packages/html/ds/src/header/components/headerDesktop.html
  packages/html/ds/src/header/components/headerMenu.html
  packages/html/ds/src/header/components/headerSearchContainer.html
  packages/html/ds/src/header/components/headerSmall.html
  packages/html/ds/src/header/header.html
  packages/html/ds/src/header/header.test.ts
Labels: bug

#232 chore: update text input with id
  packages/html/ds/src/text-input/text-input.html
  packages/html/ds/src/text-input/text-input.schema.ts
  packages/html/ds/src/text-input/text-input.stories.ts
  packages/html/ds/src/text-input/text-input.test.ts
Labels: bug

#231 feat: add global html text-area component
  apps/docs/src/lib/components.ts
  packages/html/ds/src/textarea/textarea.html
  packages/html/ds/src/textarea/textarea.schema.ts
  packages/html/ds/src/textarea/textarea.stories.ts
  packages/html/ds/src/textarea/textarea.test.ts
Labels: documentation, enhancement

#236 feat: add html select component
  examples/wagtail/core/jinja/home_page.jinja
  examples/wagtail/core/jinja/vars.jinja
  packages/html/ds/src/select/select.html
  packages/html/ds/src/select/select.schema.ts
  packages/html/ds/src/select/select.stories.ts
  packages/html/ds/src/select/select.test.ts
Labels: documentation, enhancement

#240 feat: react select component
  apps/docs/content/3-components/2-library/33-select.mdx
  apps/docs/src/lib/components.ts
  examples/vite/src/application.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/src/select/select.stories.ts
  packages/react/ds/src/select/select.tsx
Labels: documentation, enhancement

#237 chore: update `TextArea` and `TextInput` with label, error and hint props
  examples/vite/src/application.tsx
  examples/wagtail/core/jinja/home_page.jinja
  packages/html/ds/src/text-input/text-input.html
  packages/html/ds/src/text-input/text-input.schema.ts
  packages/html/ds/src/text-input/text-input.stories.ts
  packages/html/ds/src/text-input/text-input.test.ts
  packages/html/ds/src/textarea/textarea.html
  packages/html/ds/src/textarea/textarea.schema.ts
  packages/html/ds/src/textarea/textarea.stories.ts
  packages/html/ds/src/textarea/textarea.test.ts
  packages/react/ds/src/form-group/form-group.tsx
  packages/react/ds/src/hint-text/hint-text.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/src/text-input/text-input.stories.tsx
  packages/react/ds/src/text-input/text-input.tsx
  packages/react/ds/src/textarea/textarea.stories.tsx
  packages/react/ds/src/textarea/textarea.tsx
Labels: enhancement

#243 chore(ci): release main
  .release-please-manifest.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#244 chore(ci): release main
  .release-please-manifest.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#245 chore(ci): release main
  .release-please-manifest.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
Labels: autorelease: pending

#248 chore(ci): release main
  .release-please-manifest.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#247 feat: add file upload component
  apps/docs/content/3-components/2-library/14-file-upload.mdx
  apps/docs/dictionary.txt
  apps/docs/src/lib/components.ts
  examples/vite/src/application.tsx
  packages/react/ds/src/file-upload/file-upload.stories.tsx
  packages/react/ds/src/file-upload/file-upload.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/styles.css
Labels: documentation, enhancement
