Repository ogcio/govie-ds, pull requests merged in 2024-11, with the labels that each got.

#308 docs: update component usage guideline
  apps/docs/content/3-components/2-library/10-checkbox.mdx
  apps/docs/content/3-components/2-library/17-file-upload.mdx
  apps/docs/content/3-components/2-library/22-icon-button.mdx
  apps/docs/content/3-components/2-library/24-label.mdx
  apps/docs/content/3-components/2-library/25-link.mdx
  apps/docs/content/3-components/2-library/35-section-break.mdx
  apps/docs/content/3-components/2-library/36-select.mdx
  apps/docs/content/3-components/2-library/43-text-input.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/lib/components.ts
  packages/html/ds/src/label/label.stories.ts
  packages/react/ds/src/checkbox/checkbox.stories.tsx
  packages/react/ds/src/checkbox/checkboxes-group.tsx
  packages/react/ds/src/checkbox/checkboxes.test.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/src/test-utils.ts
  packages/react/ds/src/text-input/text-input.test.tsx
  packages/react/ds/src/textarea/textarea.test.tsx
Labels: documentation

#310 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#313 chore(ci): release main
  .release-please-manifest.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
Labels: autorelease: pending

#316 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/build/eslint-config/CHANGELOG.md
  packages/build/eslint-config/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#322 fix: adding rounded border for input fields
  packages/design/tailwind/css/components.css
  packages/html/ds/src/button/button.stories.ts
  packages/html/ds/src/chip/chip.stories.ts
  packages/html/ds/src/file-upload/file-upload.html
  packages/html/ds/src/link/link.stories.ts
  packages/html/ds/src/select/select.html
  packages/html/ds/src/tabs/tabs.stories.ts
  packages/html/ds/src/tabs/tabs.ts
  packages/html/ds/src/text-input/text-input.html
  packages/html/ds/src/textarea/textarea.html
  packages/react/ds/src/chip/chip.stories.tsx
  packages/react/ds/src/file-upload/file-upload.tsx
  packages/react/ds/src/link/link.stories.tsx
  packages/react/ds/src/select/select.tsx
  packages/react/ds/src/tabs/tab-item.tsx
  packages/react/ds/src/tabs/tab-list.tsx
  packages/react/ds/src/tabs/tabs.stories.tsx
  packages/react/ds/src/text-input/text-input.tsx
  packages/react/ds/src/textarea/textarea.tsx
Labels: enhancement

#320 feat: alert component
  examples/nextjs/src/app/page.tsx
  examples/vite/package.json
  examples/vite/src/application.tsx
  examples/vite/src/main.tsx
  examples/vite/src/props.tsx
  examples/wagtail/core/jinja/home_page.jinja
  packages/design/tailwind/css/components.css
  packages/html/ds/src/alert/alert-schema.ts
  packages/html/ds/src/alert/alert.html
  packages/html/ds/src/alert/alert.stories.ts
  packages/html/ds/src/alert/alert.test.ts
  packages/html/ds/src/alert/alert.ts
  packages/html/ds/src/alert/helpers.html
  packages/html/ds/src/common/instances.ts
  packages/html/ds/src/index.ts
  packages/react/ds/src/alert/alert.stories.tsx
  packages/react/ds/src/alert/alert.test.tsx
  packages/react/ds/src/alert/alert.tsx
  packages/react/ds/src/icon/icon.tsx
  packages/react/ds/src/index.ts
  pnpm-lock.yaml
Labels: documentation, enhancement

#324 fix: radio feedback fixes
  apps/docs/content/3-components/2-library/32-radio-button.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/form/radio.tsx
  examples/nextjs/src/app/page.tsx
  examples/vite/src/application.tsx
  examples/wagtail/core/jinja/home_page.jinja
  examples/wagtail/core/jinja/vars.jinja
  packages/html/ds/src/radio/radio-group.stories.ts
  packages/html/ds/src/radio/radio.html
  packages/html/ds/src/radio/radio.schema.ts
  packages/html/ds/src/radio/radio.stories.ts
  packages/html/ds/src/radio/radio.test.ts
  packages/html/ds/src/radio/radio.ts
  packages/html/ds/src/radio/radios-group.html
  packages/react/ds/src/index.ts
  packages/react/ds/src/radio/radio-group.stories.tsx
  packages/react/ds/src/radio/radio.stories.tsx
  packages/react/ds/src/radio/radio.test.tsx
  packages/react/ds/src/radio/radio.tsx
  packages/react/ds/src/radio/radios-group.tsx
  packages/react/ds/src/radio/types.ts
  packages/react/storybook/.storybook/preview.tsx
Labels: bug, enhancement

#325 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#323 feat: add react pagination component
  apps/docs/content/3-components/2-library/27-pagination.mdx
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/lib/components.ts
  examples/vite/src/application.tsx
  packages/design/tailwind/css/components.css
  packages/react/ds/src/button/button.test.tsx
  packages/react/ds/src/button/button.tsx
  packages/react/ds/src/hooks/use-breakpoint.ts
  packages/react/ds/src/index.ts
  packages/react/ds/src/pagination/pagination.stories.tsx
  packages/react/ds/src/pagination/pagination.test.tsx
  packages/react/ds/src/pagination/pagination.tsx
  packages/react/ds/src/utils/utils.test.ts
  packages/react/ds/src/utils/utils.ts
Labels: documentation, enhancement

#333 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#336 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#337 fix: pagination consistent width across html and react platforms
  apps/docs/content/3-components/2-library/pagination.mdx
  apps/docs/dictionary.txt
  packages/design/tailwind/css/components.css
  packages/html/ds/src/button/button.html
  packages/html/ds/src/pagination/pagination.html
  packages/react/ds/src/pagination/pagination.tsx
Labels: bug, documentation

#343 fix: replace push method with append
  examples/wagtail/core/jinja/home_page.jinja
  packages/html/ds/src/pagination/pagination.html
  packages/html/macro/src/macro.ts
Labels: bug

#342 fix: jinja macro - list error on home page example
  examples/wagtail/core/jinja/home_page.jinja
  packages/html/ds/src/list/list.html
Labels: documentation, enhancement

#344 feat: search pattern
  apps/docs/content/4-patterns/2-pages/1-basic-page.mdx
  apps/docs/content/4-patterns/2-pages/4-search-page.mdx
  apps/docs/dictionary.txt
  apps/docs/public/templates/search-page.html
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/components/document/patterns/render-page.tsx
  examples/wagtail/core/jinja/home_page.jinja
  examples/wagtail/core/jinja/search-page-template/search_page.jinja
  examples/wagtail/core/jinja/search-page-template/vars.jinja
  packages/html/ds/src/header/header.html
Labels: documentation, enhancement
