Repository ogcio/govie-ds, pull requests merged in 2025-08, with the labels that each got.

#666 fix: update modal for server side app and documentation structure
  apps/docs/content/3-components/2-library/modal.mdx
  apps/docs/content/3-components/2-library/modal/design.mdx
  apps/docs/content/3-components/2-library/modal/html.mdx
  apps/docs/content/3-components/2-library/modal/react.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  examples/nextjs/src/app/page.tsx
  packages/react/ds/src/button/button.tsx
  packages/react/ds/src/modal/modal.tsx
Labels: bug, documentation

#672 fix: update textarea for react hook form
  examples/nextjs/src/app/page.tsx
  packages/react/ds/src/list/list.tsx
  packages/react/ds/src/textarea/textarea.stories.tsx
  packages/react/ds/src/textarea/textarea.tsx
Labels: bug

#667 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#680 fix: remove table styling from card image
  packages/design/tailwind/css/components/card.css
Labels: bug

#681 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#683 fix: update input text component to accept react node for icon start/end
  apps/docs/content/3-components/2-library/input-text/react.mdx
  apps/docs/dictionary.txt
  packages/react/ds/src/input-text/input-text.stories.tsx
  packages/react/ds/src/input-text/input-text.tsx
  packages/react/ds/src/input-text/type.ts
Labels: documentation, enhancement

#682 fix: toggle menu label visibility
  apps/docs/content/3-components/2-library/header/react.mdx
  packages/html/ds/src/helpers/breadcrumbs.ts
  packages/html/ds/src/helpers/list.ts
  packages/react/ds/src/header/header.stories.tsx
  packages/react/ds/src/header/header.tsx
  packages/react/ds/src/header/types.ts
  packages/react/ds/src/i18n/translations/en.json
Labels: documentation, enhancement

#687 fix: add progress stepper step states AB#30471
  packages/react/ds/src/progress-stepper/progress-stepper.stories.tsx
  packages/react/ds/src/progress-stepper/progress-stepper.test.tsx
  packages/react/ds/src/progress-stepper/progress-stepper.tsx
  packages/react/ds/src/progress-stepper/types.ts
Labels: documentation, enhancement

#695 chore: update example page layout and formatting
  examples/nextjs/src/app/page.tsx
Labels: enhancement

#694 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#696 fix: update data grid pagination with select AB#30388
  packages/react/ds/src/data-grid/tanstack/tanstack.stories.tsx
  packages/react/ds/src/i18n/translations/en.json
  packages/react/ds/src/table/table-pagination.tsx
Labels: documentation, enhancement

#704 fix: add table with no border AB#30709
  packages/design/tailwind/css/components/table.css
  packages/html/ds/src/helpers/table.ts
  packages/html/ds/src/table/table.stories.tsx
  packages/html/ds/src/table/types.ts
  packages/react/ds/src/table/table.stories.tsx
  packages/react/ds/src/table/table.tsx
Labels: bug
