Repository ogcio/govie-ds, pull requests merged in 2025-05, with the labels that each got.

#540 feat: Add side navigation component to React and HTML library
  apps/docs/content/3-components/2-library/side-nav.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  packages/design/tailwind/css/components.css
  packages/design/tailwind/css/components/side-nav.css
  packages/html/ds/src/side-nav/side-nav.stories.ts
  packages/html/ds/src/side-nav/types.ts
  packages/react/ds/src/combo-box/dropdown-item.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/src/side-nav/side-nav.stories.tsx
  packages/react/ds/src/side-nav/side-nav.tsx
  packages/react/ds/src/side-nav/types.ts
Labels: documentation, enhancement

#542 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#545 fix: update side navigation
  apps/docs/content/3-components/2-library/side-nav.mdx
  apps/docs/src/components/navigation/side-navigation-connected.tsx
  apps/docs/src/components/navigation/side-navigation.tsx
  apps/docs/src/components/navigation/use-side-navigation-items.tsx
  packages/design/tailwind/css/components/side-nav.css
  packages/html/ds/src/side-nav/side-nav.stories.ts
  packages/html/ds/src/side-nav/types.ts
  packages/react/ds/src/side-nav/side-nav.stories.tsx
  packages/react/ds/src/side-nav/side-nav.tsx
  packages/react/ds/src/side-nav/types.ts
Labels: bug, documentation

#548 docs: add loading pattern
  apps/docs/content/4-patterns/2-pages/6-loading.mdx
  apps/docs/src/app/[...slug]/page.tsx
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/components/document/patterns/loading.tsx
Labels: documentation

#549 fix: add placeholder option on select
  packages/html/ds/src/helpers/forms.tsx
  packages/html/ds/src/select/select.stories.ts
  packages/html/ds/src/select/types.ts
  packages/react/ds/src/select/select.stories.tsx
Labels: bug

#547 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#552 fix: Update Progress Stepper label as optional
  packages/html/ds/src/helpers/progress-stepper.ts
  packages/html/ds/src/progress-stepper/progress-stepper.stories.ts
  packages/html/ds/src/progress-stepper/types.ts
  packages/react/ds/src/progress-stepper/progress-stepper.stories.tsx
  packages/react/ds/src/progress-stepper/progress-stepper.tsx
  packages/react/ds/src/progress-stepper/types.ts
Labels: bug

#553 fix: update combo box focus state
  apps/docs/content/3-components/2-library/combo-box.mdx
  packages/design/tailwind/css/components/combo-box.css
  packages/html/ds/src/helpers/combobox.ts
  packages/react/ds/src/combo-box/dropdown-item.tsx
Labels: bug

#555 chore: combo box class name
  packages/react/ds/src/combo-box/dropdown-item.tsx
Labels: bug

#556 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#559 docs: refactor Input Text documentation structure
  apps/docs/content/3-components/2-library/input-text.mdx
  apps/docs/content/3-components/2-library/input-text/design.mdx
  apps/docs/content/3-components/2-library/input-text/html.mdx
  apps/docs/content/3-components/2-library/input-text/react.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/components/component-preview.tsx
Labels: documentation

#562 docs: update input file structure and add figma preview button
  apps/docs/content/3-components/2-library/button-group/design.mdx
  apps/docs/content/3-components/2-library/buttons/design.mdx
  apps/docs/content/3-components/2-library/input-file.mdx
  apps/docs/content/3-components/2-library/input-file/design.mdx
  apps/docs/content/3-components/2-library/input-file/html.mdx
  apps/docs/content/3-components/2-library/input-file/react.mdx
  apps/docs/content/3-components/2-library/input-text/design.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/components/document/components/figma-preview-button.tsx
Labels: documentation

#564 docs: update input checkbox, password and radio documentation
  apps/docs/content/3-components/2-library/input-checkbox.mdx
  apps/docs/content/3-components/2-library/input-checkbox/design.mdx
  apps/docs/content/3-components/2-library/input-checkbox/html.mdx
  apps/docs/content/3-components/2-library/input-checkbox/react.mdx
  apps/docs/content/3-components/2-library/input-password.mdx
  apps/docs/content/3-components/2-library/input-password/design.mdx
  apps/docs/content/3-components/2-library/input-password/react.mdx
  apps/docs/content/3-components/2-library/input-radio.mdx
  apps/docs/content/3-components/2-library/input-radio/design.mdx
  apps/docs/content/3-components/2-library/input-radio/html.mdx
  apps/docs/content/3-components/2-library/input-radio/react.mdx
  apps/docs/content/3-components/2-library/input-text/react.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/tabs.tsx
  apps/docs/src/components/document/components/section.tsx
  packages/html/ds/src/helpers/card.ts
  packages/react/ds/src/card/card.tsx
  packages/react/ds/src/input-text/input-text.stories.tsx
  packages/react/ds/src/input-text/type.ts
Labels: documentation

#565 fix: update link styling
  packages/design/tailwind/css/typography.css
  packages/html/ds/src/link/link.stories.ts
  packages/react/ds/src/link/link.stories.tsx
Labels: bug

#566 docs: add temporary helper for new folder structure
  apps/docs/src/components/document/components/component-status-table.tsx
  apps/docs/src/lib/helper.ts
  packages/html/ds/src/file-upload/file-upload.stories.ts
Labels: bug, documentation

#568 chore: refactor input file for html
  apps/docs/content/3-components/2-library/input-file/html.mdx
  apps/docs/content/3-components/2-library/input-file/react.mdx
  packages/design/tailwind/css/components.css
  packages/design/tailwind/css/components/input-file.css
  packages/html/ds/src/helpers/forms.tsx
  packages/html/ds/src/input-file/input-file.stories.ts
  packages/html/ds/src/input-file/types.ts
Labels: bug, documentation
