Repository ogcio/govie-ds, pull requests merged in 2025-09, with the labels that each got.

#706 feat: add data grid filter options AB#30385
  apps/docs/src/components/document/data-grid/sample-data.ts
  packages/react/ds/src/data-grid/data-grid-header.tsx
  packages/react/ds/src/data-grid/tanstack/tanstack-helpers.ts
  packages/react/ds/src/data-grid/tanstack/tanstack.stories.tsx
  packages/react/ds/src/i18n/translations/en.json
  packages/react/ds/tests/visual.spec.ts-snapshots/data-grid-tanstack--data-grid-header-basic-android-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/data-grid-tanstack--data-grid-header-basic-iphone-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/form-autocomplete--default-android-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/form-autocomplete--default-firefox-linux.png
Labels: documentation, enhancement

#644 docs: add supported browsers page AB#29608
  apps/docs/content/1-get-started/4-developers/1-overview.mdx
  apps/docs/content/1-get-started/4-developers/2-supported-browsers.mdx
  packages/react/ds/.storybook/main.ts
Labels: documentation

#720 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#733 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#738 fix: update data table footer and header with styling improvements AB#31357
  packages/design/tailwind/css/components.css
  packages/design/tailwind/css/components/data-table.css
  packages/design/tailwind/css/components/table.css
  packages/react/ds/src/data-table/data-table-footer.tsx
  packages/react/ds/src/data-table/data-table-header.tsx
  packages/react/ds/src/data-table/tanstack/tanstack.stories.tsx
  packages/react/ds/src/table/table-pagination.tsx
  packages/react/ds/tests/visual.spec.ts-snapshots/components-table--table-with-footer-android-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/components-table--table-with-footer-chromium-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/components-table--table-with-footer-firefox-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/components-table--table-with-footer-iphone-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/components-table--table-with-footer-webkit-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/data-table-tanstack--data-table-footer-basic-android-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/data-table-tanstack--data-table-footer-basic-chromium-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/data-table-tanstack--data-table-footer-basic-firefox-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/data-table-tanstack--data-table-footer-basic-iphone-linux.png
  packages/react/ds/tests/visual.spec.ts-snapshots/data-table-tanstack--data-table-footer-basic-webkit-linux.png
Labels: bug, documentation, enhancement
