Repository ogcio/govie-ds, pull requests merged in 2025-02, with the labels that each got.

#419 fix: update tooltip with escape and focus functionality
  packages/design/tailwind/css/components.css
  packages/html/ds/src/tooltip/tooltip.stories.ts
  packages/html/ds/src/tooltip/tooltip.test.ts
  packages/html/ds/src/tooltip/tooltip.ts
  packages/react/ds/src/tooltip/tooltip.stories.tsx
  packages/react/ds/src/tooltip/tooltip.test.tsx
  packages/react/ds/src/tooltip/tooltip.tsx
Labels: documentation, enhancement

#425 chore(ci): release main
  .release-please-manifest.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#429 chore: update table storybook with loading state
  packages/design/tailwind/css/components.css
  packages/react/ds/src/table/table.stories.tsx
Labels: documentation

#431 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#440 chore: update example vite app with correct usage of toast
  examples/vite/src/application.tsx
Labels: bug

#436 docs: refactor addresses pattern with code example
  apps/docs/content/4-patterns/1-ask-users-for/1-addresses.mdx
  apps/docs/content/4-patterns/1-ask-users-for/2-contact-dept-or-service.mdx
  apps/docs/public/addresses-pattern.png
  apps/docs/public/addresses-with-textarea-pattern.png
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/components/document/patterns/addresses.tsx
Labels: documentation, enhancement

#439 fix: update container max width
  apps/docs/content/3-components/2-library/container.mdx
  apps/docs/dictionary.txt
  packages/design/tailwind/css/layout.css
Labels: enhancement

#435 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#434 chore: update card to accept custom aspect ratio
  packages/design/tailwind/css/components.css
  packages/html/ds/src/card/card.html
  packages/html/ds/src/card/card.schema.ts
  packages/html/ds/src/card/card.stories.ts
  packages/html/ds/src/card/card.test.ts
  packages/react/ds/src/card/card.stories.tsx
  packages/react/ds/src/card/card.test.tsx
  packages/react/ds/src/card/card.tsx
Labels: enhancement

#449 chore: update data test id for button
  packages/html/ds/src/button/button-schema.ts
  packages/html/ds/src/button/button.html
  packages/html/ds/src/button/button.test.ts
  packages/html/ds/src/pagination/pagination.html
  packages/react/ds/src/button/button.test.tsx
  packages/react/ds/src/button/button.tsx
  packages/react/ds/src/button/types.ts
Labels: documentation

#447 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/build/eslint-config/CHANGELOG.md
  packages/build/eslint-config/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#454 chore(ci): release main
  .release-please-manifest.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#452 feat: localisation
  examples/vite/src/application.tsx
  examples/vite/src/main.tsx
  packages/react/ds/.storybook/preview.tsx
  packages/react/ds/package.json
  packages/react/ds/src/i18n/config.ts
  packages/react/ds/src/i18n/translations/en.json
  packages/react/ds/src/index.ts
  packages/react/ds/src/pagination/pagination.test.tsx
  packages/react/ds/src/pagination/pagination.tsx
  pnpm-lock.yaml
Labels: documentation, enhancement
