Repository ogcio/govie-ds, pull requests merged in 2025-04, with the labels that each got.

#501 fix: update pagination and use breakpoint hook
  examples/nextjs/src/app/page.tsx
  packages/react/ds/src/hooks/use-breakpoint.ts
  packages/react/ds/src/pagination/pagination.test.tsx
  packages/react/ds/src/pagination/pagination.tsx
Labels: bug

#499 fix: update files with missing locale keys
  apps/docs/content/3-components/2-library/combo-box.mdx
  apps/docs/content/3-components/2-library/header.mdx
  apps/docs/content/3-components/2-library/pagination.mdx
  apps/docs/content/3-components/2-library/textarea.mdx
  apps/docs/dictionary.txt
  packages/react/ds/src/alert/alert.tsx
  packages/react/ds/src/breadcrumbs/breadcrumbs.tsx
  packages/react/ds/src/card/card.tsx
  packages/react/ds/src/chip/chip.tsx
  packages/react/ds/src/combo-box/dropdown-item.tsx
  packages/react/ds/src/cookie-banner/cookie-banner.tsx
  packages/react/ds/src/footer/footer.test.tsx
  packages/react/ds/src/footer/footer.tsx
  packages/react/ds/src/header/components/header-menu.tsx
  packages/react/ds/src/header/components/header-search.tsx
  packages/react/ds/src/header/components/header-slot.tsx
  packages/react/ds/src/header/header.tsx
  packages/react/ds/src/i18n/translations/en.json
  packages/react/ds/src/i18n/utility.ts
  packages/react/ds/src/pagination/pagination.tsx
  packages/react/ds/src/progress-bar/progress-bar.tsx
  packages/react/ds/src/section-break/section-break.tsx
  packages/react/ds/src/summary-list/summary-list.tsx
  packages/react/ds/src/textarea/textarea.tsx
  packages/react/ds/src/toast/toast.tsx
  packages/react/ds/tsconfig.json
Labels: enhancement

#507 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#519 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#518 feat: add button group component
  apps/docs/content/3-components/2-library/button.mdx
  apps/docs/src/components/document/common/mdx.tsx
  packages/design/tailwind/css/components/button.css
  packages/html/ds/src/button/button-group/button-group.stories.ts
  packages/html/ds/src/button/button.stories.ts
  packages/react/ds/src/button/button-group/button-group.stories.tsx
  packages/react/ds/src/button/button-group/button-group.tsx
  packages/react/ds/src/button/button.stories.tsx
  packages/react/ds/src/index.ts
Labels: documentation, enhancement

#525 feat: add score select component
  apps/docs/content/3-components/2-library/score-select.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  packages/design/tailwind/css/components.css
  packages/design/tailwind/css/components/score-select.css
  packages/html/ds/src/button/button-group/button-group.stories.ts
  packages/html/ds/src/score-select/helper.ts
  packages/html/ds/src/score-select/score-select.stories.ts
  packages/html/ds/src/score-select/types.ts
  packages/react/ds/src/button/button-group/button-group.stories.tsx
  packages/react/ds/src/button/button-group/button-group.tsx
  packages/react/ds/src/index.ts
  packages/react/ds/src/score-select/score-select.stories.tsx
  packages/react/ds/src/score-select/score-select.tsx
  packages/react/ds/src/score-select/type.ts
Labels: documentation, enhancement

#524 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#531 fix: update checkbox label width
  packages/design/tailwind/css/components/input-checkbox.css
Labels: bug

#530 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#534 chore(ci): release main
  .release-please-manifest.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
Labels: autorelease: pending

#537 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending
