Repository ogcio/govie-ds, pull requests merged in 2025-01, with the labels that each got.

#369 feat: Progress Bar component
  apps/docs/content/3-components/2-library/progress-bar.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/common/mdx.tsx
  examples/nextjs/src/app/page.tsx
  examples/wagtail/core/jinja/home_page.jinja
  packages/design/tailwind/css/components.css
  packages/html/ds/src/progress-bar/progress-bar.html
  packages/html/ds/src/progress-bar/progress-bar.schema.ts
  packages/html/ds/src/progress-bar/progress-bar.stories.ts
  packages/html/ds/src/progress-bar/progress-bar.test.ts
  packages/react/ds/src/index.ts
  packages/react/ds/src/progress-bar/progress-bar.stories.tsx
  packages/react/ds/src/progress-bar/progress-bar.test.tsx
  packages/react/ds/src/progress-bar/progress-bar.tsx
Labels: documentation, enhancement

#385 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#387 fix: add iframe media type to card component
  apps/docs/content/3-components/2-library/card.mdx
  examples/vite/src/application.tsx
  packages/design/tailwind/css/components.css
  packages/html/ds/scripts/build-properties.ts
  packages/html/ds/src/card/card.html
  packages/html/ds/src/card/card.schema.ts
  packages/html/ds/src/card/card.stories.ts
  packages/html/ds/src/card/card.test.ts
  packages/react/ds/src/card/card.stories.tsx
  packages/react/ds/src/card/card.test.tsx
  packages/react/ds/src/card/card.tsx
Labels: documentation, enhancement

#386 fix: add aria attributes for text-input, checkbox, radio, button, link and tooltip
  packages/html/ds/src/button/button.html
  packages/html/ds/src/checkbox/checkbox.html
  packages/html/ds/src/checkbox/checkbox.stories.ts
  packages/html/ds/src/checkbox/checkbox.ts
  packages/html/ds/src/checkbox/checkboxes.schema.ts
  packages/html/ds/src/checkbox/checkboxes.test.ts
  packages/html/ds/src/link/link.html
  packages/html/ds/src/link/link.schema.ts
  packages/html/ds/src/link/link.stories.ts
  packages/html/ds/src/link/link.test.ts
  packages/html/ds/src/radio/radio.html
  packages/html/ds/src/radio/radio.schema.ts
  packages/html/ds/src/radio/radio.stories.ts
  packages/html/ds/src/radio/radio.test.ts
  packages/html/ds/src/radio/radio.ts
  packages/html/ds/src/text-input/text-input.html
  packages/html/ds/src/text-input/text-input.schema.ts
  packages/html/ds/src/text-input/text-input.stories.ts
  packages/html/ds/src/text-input/text-input.test.ts
  packages/html/ds/src/tooltip/tooltip.html
  packages/html/ds/src/tooltip/tooltip.schema.ts
  packages/html/ds/src/tooltip/tooltip.stories.ts
  packages/html/ds/src/tooltip/tooltip.test.ts
Labels: enhancement

#392 chore(ci): release main
  .release-please-manifest.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#396 fix: update radio min width and height
  packages/design/tailwind/css/components.css
Labels: bug

#395 chore: Aria attributes for missing macro/html components
  packages/html/ds/src/accordion/accordion-schema.ts
  packages/html/ds/src/accordion/accordion.html
  packages/html/ds/src/accordion/accordion.stories.ts
  packages/html/ds/src/breadcrumbs/breadcrumbs.html
  packages/html/ds/src/file-upload/file-upload.html
  packages/html/ds/src/modal/modal.html
  packages/html/ds/src/modal/modal.schema.ts
  packages/html/ds/src/modal/modal.stories.ts
  packages/html/ds/src/modal/modal.test.ts
  packages/html/ds/src/modal/modal.ts
  packages/html/ds/src/pagination/pagination.html
  packages/html/ds/src/section-break/section-break.html
  packages/html/ds/src/select/select.html
  packages/html/ds/src/summary-list/summary-list.html
  packages/html/ds/src/table/table.html
  packages/html/ds/src/table/table.schema.ts
  packages/html/ds/src/table/table.stories.ts
  packages/html/ds/src/table/table.test.ts
  packages/html/ds/src/tag/tag.html
  packages/html/ds/src/tag/tag.schema.ts
  packages/html/ds/src/tag/tag.stories.ts
  packages/html/ds/src/tag/tag.test.ts
  packages/html/ds/src/text-input/text-input.stories.ts
Labels: documentation, enhancement

#400 feat: add layout page example
  apps/docs/content/4-patterns/2-pages/5-layout-page.mdx
  apps/docs/public/templates/layout-page.html
  apps/docs/src/components/document/patterns/render-page.tsx
  packages/design/tailwind/css/layout.css
Labels: documentation, enhancement

#398 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#405 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#414 docs: update summary list row display name on storybook
  packages/react/ds/src/summary-list/summary-list.tsx
Labels: bug

#415 chore: add accordion react unit tests.
  packages/react/ds/src/accordion/accordion.test.tsx
Labels: documentation

#417 fix: update common aria attributes
  packages/html/ds/src/common/aria-attributes.html
  packages/html/ds/src/link/link.html
  packages/html/macro/src/macro.ts
Labels: bug

#412 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending
