Repository ogcio/govie-ds, pull requests merged in 2025-06, with the labels that each got.

#574 fix: update combobox counter height and docs
  apps/docs/public/templates/search-page.html
  packages/design/tailwind/css/components/combo-box.css
Labels: bug, documentation

#583 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
  tokens/tokens/light/brand/brand.json
  tokens/tokens/light/primitive/color.json
Labels: autorelease: pending

#588 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
Labels: autorelease: pending

#585 docs: download svg icon button
  apps/docs/src/components/document/resources/copy-to-clipboard-button.tsx
  apps/docs/src/components/document/resources/download-icon-button.tsx
  apps/docs/src/components/document/resources/download-svg.tsx
  apps/docs/src/components/document/resources/logos.tsx
Labels: documentation

#586 fix: update combo box focus state
  apps/docs/content/3-components/2-library/combo-box.mdx
  packages/design/tailwind/css/components/combo-box.css
  packages/html/ds/src/helpers/combobox.ts
  packages/react/ds/src/combo-box/dropdown-item.tsx
Labels: bug, documentation

#594 docs: add header documentation structure
  apps/docs/content/3-components/2-library/button-group/html.mdx
  apps/docs/content/3-components/2-library/button-group/react.mdx
  apps/docs/content/3-components/2-library/card/html.mdx
  apps/docs/content/3-components/2-library/card/react.mdx
  apps/docs/content/3-components/2-library/footer/html.mdx
  apps/docs/content/3-components/2-library/footer/react.mdx
  apps/docs/content/3-components/2-library/header.mdx
  apps/docs/content/3-components/2-library/header/design.mdx
  apps/docs/content/3-components/2-library/header/html.mdx
  apps/docs/content/3-components/2-library/header/react.mdx
  apps/docs/content/3-components/2-library/input-checkbox/html.mdx
  apps/docs/content/3-components/2-library/input-checkbox/react.mdx
  apps/docs/content/3-components/2-library/input-file/html.mdx
  apps/docs/content/3-components/2-library/input-file/react.mdx
  apps/docs/content/3-components/2-library/input-password/react.mdx
  apps/docs/content/3-components/2-library/input-radio/html.mdx
  apps/docs/content/3-components/2-library/input-radio/react.mdx
  apps/docs/content/3-components/2-library/input-text/html.mdx
  apps/docs/content/3-components/2-library/input-text/react.mdx
  apps/docs/content/3-components/2-library/popover/react.mdx
  apps/docs/content/3-components/2-library/select/html.mdx
  apps/docs/content/3-components/2-library/select/react.mdx
  apps/docs/dictionary.txt
  apps/docs/src/components/document/components/storybook-frame.tsx
Labels: documentation

#605 fix: update TextArea for controlled and uncontrolled usecases
  examples/nextjs/package.json
  examples/nextjs/src/app/page.tsx
  packages/react/ds/src/textarea/textarea.tsx
  pnpm-lock.yaml
Labels: bug
