Repository ogcio/govie-ds, pull requests merged in 2025-07, with the labels that each got.

#610 chore(auto-release): release eslint-config 1.2.5
  .release-please-manifest.json
  packages/build/eslint-config/CHANGELOG.md
  packages/build/eslint-config/package.json
Labels: autorelease: pending

#607 fix: update react and html details component
  apps/docs/content/3-components/2-library/details.mdx
  apps/docs/content/3-components/2-library/details/design.mdx
  apps/docs/content/3-components/2-library/details/html.mdx
  apps/docs/content/3-components/2-library/details/react.mdx
  packages/design/tailwind/css/components.css
  packages/design/tailwind/css/components/details.css
  packages/design/tailwind/css/typography.css
  packages/html/ds/src/common/instances.ts
  packages/html/ds/src/details/details.ts
  packages/html/ds/src/helpers/details.ts
  packages/html/ds/src/index.ts
  packages/react/ds/src/details/details.test.tsx
  packages/react/ds/src/details/details.tsx
Labels: documentation, enhancement

#627 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#631 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#620 docs: update pagination documentation structure
  apps/docs/content/3-components/2-library/pagination.mdx
  apps/docs/content/3-components/2-library/pagination/design.mdx
  apps/docs/content/3-components/2-library/pagination/html.mdx
  apps/docs/content/3-components/2-library/pagination/react.mdx
  apps/docs/dictionary.txt
Labels: documentation

#633 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#636 chore(auto-release): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#640 fix: add forward ref to input password
  packages/react/ds/src/input-password/input-password.test.tsx
  packages/react/ds/src/input-password/input-password.tsx
Labels: bug

#653 fix: update InputRadio, InputCheckbox, SelectNext and TextArea with controlled props
  examples/nextjs/src/app/page.tsx
  packages/react/ds/src/button-group/button-group.stories.tsx
  packages/react/ds/src/button-group/button-group.test.tsx
  packages/react/ds/src/button-group/button-group.tsx
  packages/react/ds/src/input-checkbox-group/input-checkbox-group.stories.tsx
  packages/react/ds/src/input-checkbox-group/input-checkbox-group.tsx
  packages/react/ds/src/input-checkbox-group/types.ts
  packages/react/ds/src/input-radio-group/input-radio-group.stories.tsx
  packages/react/ds/src/input-radio-group/input-radio-group.tsx
  packages/react/ds/src/input-radio-group/types.ts
  packages/react/ds/src/input-radio/input-radio.tsx
  packages/react/ds/src/select/select-next.stories.tsx
  packages/react/ds/src/select/select-next.tsx
  packages/react/ds/src/select/types.ts
  packages/react/ds/src/textarea/textarea.stories.tsx
  packages/react/ds/src/textarea/textarea.tsx
Labels: bug

#657 fix: update header translation and associated doc fixes for i18n keys
  apps/docs/content/3-components/2-library/alert/react.mdx
  apps/docs/content/3-components/2-library/breadcrumb/react.mdx
  apps/docs/content/3-components/2-library/card/react.mdx
  apps/docs/content/3-components/2-library/chip/react.mdx
  apps/docs/content/3-components/2-library/combo-box/react.mdx
  apps/docs/content/3-components/2-library/footer/react.mdx
  apps/docs/content/3-components/2-library/header/react.mdx
  apps/docs/content/3-components/2-library/textarea/react.mdx
  packages/react/ds/src/header/components/header-slot.tsx
  packages/react/ds/src/i18n/translations/en.json
Labels: bug, documentation

#652 fix: a11y compliance
  packages/design/tailwind/css/components/input-text.css
  packages/design/tailwind/css/components/select.css
  packages/html/ds/.storybook/preview.tsx
  packages/html/ds/chromatic.config.json
  packages/html/ds/src/helpers/forms.tsx
  packages/html/ds/src/helpers/progress-stepper.ts
  packages/html/ds/src/input-checkbox/types.ts
  packages/html/ds/src/input-text/input-text.stories.ts
  packages/html/ds/src/progress-stepper/progress-stepper.content.ts
  packages/html/ds/src/select/select-native.stories.ts
  packages/html/ds/src/table/table.stories.ts
  packages/react/ds/.storybook/preview.tsx
  packages/react/ds/chromatic.config.json
  packages/react/ds/src/data-grid/editable-table-cell.stories.tsx
  packages/react/ds/src/data-grid/tanstack/tanstack.stories.tsx
  packages/react/ds/src/footer/footer.stories.tsx
  packages/react/ds/src/header/components/header-slot.tsx
  packages/react/ds/src/header/header.stories.tsx
  packages/react/ds/src/header/header.tsx
  packages/react/ds/src/i18n/translations/en.json
  packages/react/ds/src/icon-button/icon-button.test.tsx
  packages/react/ds/src/icon-button/icon-button.tsx
  packages/react/ds/src/icon/svgs/placeholder.tsx
  packages/react/ds/src/modal/modal.tsx
  packages/react/ds/src/progress-stepper/progress-stepper.stories.tsx
  packages/react/ds/src/progress-stepper/progress-stepper.tsx
  packages/react/ds/src/stack/stack.stories.tsx
  packages/react/ds/src/stack/stack.tsx
  packages/react/ds/src/table/table-data.tsx
  packages/react/ds/src/table/table-header.tsx
Labels: bug

#660 feat: add table pagination to tanstack
  packages/design/tailwind/css/components/table.css
  packages/html/ds/src/icon/icon.schema.ts
  packages/html/ds/styles.css
  packages/react/ds/src/data-grid/tanstack/tanstack.stories.tsx
  packages/react/ds/src/i18n/translations/en.json
  packages/react/ds/src/icon/icons.ts
  packages/react/ds/src/table/table-header.tsx
  packages/react/ds/src/table/table-pagination.tsx
  packages/react/ds/styles.css
Labels: documentation, enhancement

#664 docs: update progress stepper documentation structure
  apps/docs/content/3-components/2-library/progress-stepper.mdx
  apps/docs/content/3-components/2-library/progress-stepper/design.mdx
  apps/docs/content/3-components/2-library/progress-stepper/html.mdx
  apps/docs/content/3-components/2-library/progress-stepper/react.mdx
  apps/docs/dictionary.txt
Labels: documentation
