Repository ogcio/govie-ds, pull requests merged in 2025-03, with the labels that each got.

#456 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#458 docs: add grid guidelines
  apps/docs/content/2-foundations/2-design-tokens/12-grid.mdx
  apps/docs/content/4-patterns/2-pages/5-layout-page.mdx
  apps/docs/public/templates/layout-page.html
  apps/docs/src/components/document/common/mdx.tsx
  apps/docs/src/components/document/grid/grid-primitives.tsx
  packages/design/tailwind/css/layout.css
Labels: documentation, enhancement

#465 fix: update tab list checked state
  packages/react/ds/src/tabs/tab-list.tsx
  packages/react/ds/src/tabs/tabs.stories.tsx
  packages/react/ds/src/tabs/tabs.test.tsx
Labels: bug

#469 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#463 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
Labels: autorelease: pending

#475 docs: update layout page banner image
  apps/docs/public/templates/layout-page.html
  apps/docs/src/components/document/grid/grid-primitives.tsx
Labels: documentation

#473 fix: update tailwind config safelist
  packages/html/ds/tailwind.config.ts
  packages/react/ds/tailwind.config.ts
Labels: bug

#476 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#481 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/build/eslint-config/CHANGELOG.md
  packages/build/eslint-config/package.json
  packages/build/prettier-config/CHANGELOG.md
  packages/build/prettier-config/package.json
  packages/design/deepmerge/CHANGELOG.md
  packages/design/deepmerge/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#474 chore: split components css
  packages/design/tailwind/css/components.css
  packages/design/tailwind/css/components/accordion.css
  packages/design/tailwind/css/components/alert.css
  packages/design/tailwind/css/components/blockquote.css
  packages/design/tailwind/css/components/breadcrumbs.css
  packages/design/tailwind/css/components/button.css
  packages/design/tailwind/css/components/card.css
  packages/design/tailwind/css/components/checkbox.css
  packages/design/tailwind/css/components/chip.css
  packages/design/tailwind/css/components/combo-box.css
  packages/design/tailwind/css/components/common.css
  packages/design/tailwind/css/components/cookie-banner.css
  packages/design/tailwind/css/components/drawer.css
  packages/design/tailwind/css/components/error-text.css
  packages/design/tailwind/css/components/file-upload.css
  packages/design/tailwind/css/components/footer.css
  packages/design/tailwind/css/components/header.css
  packages/design/tailwind/css/components/hint-text.css
  packages/design/tailwind/css/components/icon-button.css
  packages/design/tailwind/css/components/input-group.css
  packages/design/tailwind/css/components/label.css
  packages/design/tailwind/css/components/modal.css
  packages/design/tailwind/css/components/pagination.css
  packages/design/tailwind/css/components/phase-banner.css
  packages/design/tailwind/css/components/progress-bar.css
  packages/design/tailwind/css/components/progress-stepper.css
  packages/design/tailwind/css/components/radio.css
  packages/design/tailwind/css/components/section-break.css
  packages/design/tailwind/css/components/select.css
  packages/design/tailwind/css/components/table.css
  packages/design/tailwind/css/components/tabs.css
  packages/design/tailwind/css/components/tag.css
  packages/design/tailwind/css/components/text-area.css
  packages/design/tailwind/css/components/text-input.css
  packages/design/tailwind/css/components/toast.css
  packages/design/tailwind/css/components/tootlip.css
Labels: documentation

#464 docs: main height adjusted
  apps/docs/src/app/[...slug]/layout.tsx
  apps/docs/src/app/contact/page.tsx
  apps/docs/src/app/layout.tsx
Labels: documentation

#477 feat: update footer with slots
  apps/docs/content/3-components/2-library/footer.mdx
  apps/docs/src/app/layout.tsx
  examples/vite/src/application.tsx
  packages/design/tailwind/css/components/footer.css
  packages/design/tailwind/css/components/section-break.css
  packages/html/ds/.storybook/preview.tsx
  packages/html/ds/package.json
  packages/html/ds/src/footer/footer.html
  packages/html/ds/src/footer/footer.schema.ts
  packages/html/ds/src/footer/footer.stories.ts
  packages/html/ds/src/footer/footer.test.ts
  packages/html/ds/src/footer/footer.util.ts
  packages/html/ds/src/section-break/section-break.html
  packages/html/ds/src/section-break/section-break.schema.ts
  packages/html/ds/src/section-break/section-break.stories.ts
  packages/html/ds/src/storybook/storybook.tsx
  packages/react/ds/src/common/types.ts
  packages/react/ds/src/footer/footer.stories.tsx
  packages/react/ds/src/footer/footer.test.tsx
  packages/react/ds/src/footer/footer.tsx
  packages/react/ds/src/header/types.ts
  packages/react/ds/src/section-break/section-break.tsx
  pnpm-lock.yaml
Labels: documentation, enhancement

#489 fix: update dropdown item with additional props
  packages/react/ds/src/combo-box/combo-box.stories.tsx
  packages/react/ds/src/combo-box/dropdown-item.test.tsx
  packages/react/ds/src/combo-box/dropdown-item.tsx
  packages/react/ds/src/combo-box/types.ts
Labels: bug

#488 fix: update disabled property select and select item
  packages/design/tailwind/css/components/select.css
  packages/react/ds/src/select/select.stories.tsx
Labels: bug

#483 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/build/eslint-config/CHANGELOG.md
  packages/build/eslint-config/package.json
  packages/build/prettier-config/CHANGELOG.md
  packages/build/prettier-config/package.json
  packages/design/deepmerge/CHANGELOG.md
  packages/design/deepmerge/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#487 docs: add component prop types
  apps/docs/content/3-components/2-library/accordion.mdx
  apps/docs/content/3-components/2-library/alert.mdx
  apps/docs/content/3-components/2-library/blockquote.mdx
  apps/docs/content/3-components/2-library/breadcrumbs.mdx
  apps/docs/content/3-components/2-library/button.mdx
  apps/docs/content/3-components/2-library/card.mdx
  apps/docs/content/3-components/2-library/checkbox.mdx
  apps/docs/content/3-components/2-library/chip.mdx
  apps/docs/content/3-components/2-library/combo-box.mdx
  apps/docs/content/3-components/2-library/cookie-banner.mdx
  apps/docs/content/3-components/2-library/details.mdx
  apps/docs/content/3-components/2-library/drawer.mdx
  apps/docs/content/3-components/2-library/file-upload.mdx
  apps/docs/content/3-components/2-library/footer.mdx
  apps/docs/content/3-components/2-library/header.mdx
  apps/docs/content/3-components/2-library/heading.mdx
  apps/docs/content/3-components/2-library/icon-button.mdx
  apps/docs/content/3-components/2-library/icon.mdx
  apps/docs/content/3-components/2-library/link.mdx
  apps/docs/content/3-components/2-library/list.mdx
  apps/docs/content/3-components/2-library/pagination.mdx
  apps/docs/content/3-components/2-library/paragraph.mdx
  apps/docs/content/3-components/2-library/phase-banner.mdx
  apps/docs/content/3-components/2-library/progress-bar.mdx
  apps/docs/content/3-components/2-library/radio-button.mdx
  apps/docs/content/3-components/2-library/section-break.mdx
  apps/docs/content/3-components/2-library/select.mdx
  apps/docs/content/3-components/2-library/spinner.mdx
  apps/docs/content/3-components/2-library/stack.mdx
  apps/docs/content/3-components/2-library/summary-list.mdx
  apps/docs/content/3-components/2-library/table.mdx
  apps/docs/content/3-components/2-library/tabs.mdx
  apps/docs/content/3-components/2-library/tag.mdx
  apps/docs/content/3-components/2-library/text-input.mdx
  apps/docs/content/3-components/2-library/textarea.mdx
  apps/docs/content/3-components/2-library/toast.mdx
  apps/docs/content/3-components/2-library/tooltip.mdx
  apps/docs/dictionary.txt
Labels: documentation

#496 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/build/eslint-config/CHANGELOG.md
  packages/build/eslint-config/package.json
  packages/build/prettier-config/CHANGELOG.md
  packages/build/prettier-config/package.json
  packages/design/deepmerge/CHANGELOG.md
  packages/design/deepmerge/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending

#497 chore(ci): release main
  .release-please-manifest.json
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/build/eslint-config/CHANGELOG.md
  packages/build/eslint-config/package.json
  packages/build/prettier-config/CHANGELOG.md
  packages/build/prettier-config/package.json
  packages/design/deepmerge/CHANGELOG.md
  packages/design/deepmerge/package.json
  packages/design/tailwind/CHANGELOG.md
  packages/design/tailwind/package.json
  packages/design/theme-builder/CHANGELOG.md
  packages/design/theme-builder/package.json
  packages/html/ds/CHANGELOG.md
  packages/html/ds/package.json
  packages/react/ds/CHANGELOG.md
  packages/react/ds/package.json
  packages/themes/govie/CHANGELOG.md
  packages/themes/govie/package.json
  tokens/CHANGELOG.md
  tokens/package.json
Labels: autorelease: pending
